name: 3. Branch on Workflow Run

# Este workflow demonstra como usar filtros de branch (`branches` e `branches-ignore`)
# no gatilho `workflow_run`. Isso permite um controle extremamente poderoso, garantindo
# que uma a칞칚o (como um deploy) s칩 seja acionada quando o workflow de origem
# for executado em uma branch espec칤fica.
#
# Caso de uso principal:
# - CI/CD: Executar um workflow de deploy para produ칞칚o SOMENTE QUANDO o workflow de
#   testes e build for conclu칤do com SUCESSO na branch `main`. Isso evita deploys
#   acidentais a partir de branches de feature.

on:
  workflow_run:
    # O nome do workflow que acionar치 este.
    # IMPORTANTE: Substitua pelo nome exato do seu workflow de CI.
    workflows: ["Meu Primeiro Workflow de CI"]

    # O evento que aciona. 'completed' significa que ele rodar치 ap칩s o outro workflow terminar.
    types:
      - completed

    # AQUI EST츼 A CHAVE: Filtro de Branch
    # Este workflow s칩 ser치 acionado se o workflow "Meu Primeiro Workflow de CI"
    # foi executado na branch `main`. Se o mesmo workflow rodar em uma branch
    # `develop` ou `feature/nova-func`, este workflow aqui ser치 ignorado.
    branches:
      - main

jobs:
  # Este job simula um deploy para produ칞칚o, que s칩 deve ocorrer a partir da branch `main`.
  deploy-to-production:
    runs-on: ubuntu-latest
    # Adicionamos uma verifica칞칚o dupla para garantir que o deploy s칩 ocorra
    # se o workflow anterior teve sucesso.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy para Produ칞칚o
        run: |
          echo "游 O workflow '${{ github.event.workflow_run.workflow.name }}' foi conclu칤do com sucesso na branch 'main'."
          echo "Iniciando o processo de deploy para o ambiente de produ칞칚o..."
          # Aqui entrariam os passos reais de deploy:
          # - actions/checkout@v3
          # - aws-actions/configure-aws-credentials@v2
          # - aws s3 sync . s3://meu-bucket-de-producao